/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:67510c68-448e-4907-a9a3-b70b74b0ebf2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_YiqDNArYn",
    "aws_user_pools_web_client_id": "5j1suiml04d6fg4feiloh349ml",
    "oauth": {}
};


export default awsmobile;
